public without sharing class HOT_EntitlementController {
    // @AuraEnabled(cacheable=true)
    // public static HOT_Entitlement__c getEntitlements(){
    //         User currentUser = [SELECT Id, AccountId FROM User WHERE Id = :UserInfo.getUserId()];
    //         HOT_Entitlement__c entitlements = [
    //         SELECT Id
    //         FROM HOT_Entitlement__c
    //     ];
    //     return entitlements;
    // }
}